---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.name }}
spec:
  dnsNames:
  - {{ .Values.dnsName | quote }}
  issuerRef:
    name: cert-manager-webhook-duckdns-production
    kind: ClusterIssuer
  secretName: "{{ .Values.name }}-tls"
