---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.name }}
spec:
  dnsNames:
  - "*.{{ .Values.name }}.{{ .Values.domain.domainname }}"
  issuerRef:
    name: "{{ .Values.name }}-{{ .Values.domain.domainprovider }}"
    kind: ClusterIssuer
  secretName: "{{ .Values.name }}-tls"