apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.name }}-{{ .Values.domain.domainprovider }}"
  namespace: cert-manager
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  token: {{ .Values.domain.token | quote }}