---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: {{ .Values.namespace }}
    istio.io/dataplane-mode: {{ index .Values "dataplane-mode" }}
  name: {{ .Values.namespace }}
