apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Values.host | replace "." "-" }}
  namespace: "istio-system"
spec:
  selector:
    app: "istio-gateway"
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.host }}
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "{{ .Values.name }}-tls"
    hosts:
    - {{ .Values.host }}
