---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: {{ .Values.namespace }}
    istio.io/dataplane-mode: {{ index .Values "dataplane-mode" }}
  name: {{ .Values.namespace }}
---
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Values.host | replace "." "-" }}
  namespace: "istio-system"
spec:
  selector:
    app: "istio-gateway"
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.host }}
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "{{ .Values.name }}-tls"
    hosts:
    - {{ .Values.host }}
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Values.host | replace "." "-" }}
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - {{ .Values.host }}
  gateways:
  - "istio-system/{{ .Values.host | replace "." "-" }}"
  http:
  - route:
    - destination:
        host: {{ .Values.service }}
        port:
          number: {{ .Values.port }}