apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Values.host | replace "." "-" }}
  annotations:
    external-dns.alpha.kubernetes.io/target: {{ .Values.target }}
spec:
  hosts:
  - {{ .Values.host }}
  gateways:
  - "istio-system/{{ .Values.host | replace "." "-" }}"
  http:
  - route:
    - destination:
        host: {{ .Values.service }}
        port:
          number: {{ .Values.port }}
