name: Renovate
on:
  schedule:
    - cron: '0 18 * * 2'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Renovate
        uses: renovatebot/github-action@v40.2.7
        with:
          configurationFile: example/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}